export const SELECT_TYPE = "SELECT_TYPE";
export const SELECT_THROW_OUTCOME = "SELECT_THROW_OUTCOME";
export const SELECT_THROW_TECHNIQUE = "SELECT_THROW_TECHNIQUE";
export const SELECT_TURNOVER_TYPE = "SELECT_TURNOVER_TYPE";
export const SELECT_PUNISHMENT_TYPE = "SELECT_PUNISHMENT_TYPE";
export const SELECT_PLAYER = "SELECT_PLAYER";
